# Site settings
title: This is the home of Ivan Odbratt and my random ramblings. I'm a copywriter and editor. Based in Stockholm.
email: hello@ivanodbratt.com
description: "Random ramblings of unconstructed thoughts."
baseurl: ""
url: "http://ivanodbratt.com"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5